[package]
name = "hearth-interconnect"
version = "0.1.0"
edition = "2021"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_derive = "1.0.160"
serde = "1.0.160"
serde_json = "1.0.96"
schemars = "0.8.12"
